"""empty message

Revision ID: ab1eff6f73f5
Revises: 
Create Date: 2020-04-13 09:31:16.613208

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab1eff6f73f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('userID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=15), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('userID')
    )
    op.drop_table('users')
    op.drop_constraint('tests_ibfk_1', 'tests', type_='foreignkey')
    op.create_foreign_key(None, 'tests', 'Users', ['userID'], ['userID'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.create_foreign_key('tests_ibfk_1', 'tests', 'users', ['userID'], ['userID'])
    op.create_table('users',
    sa.Column('userID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('score', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('userID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Users')
    # ### end Alembic commands ###
